### PR TITLE
[WIP] MQTT support

### PR DESCRIPTION
**Pull request by jooert**
This is a first stab at MQTT support (see #14). I tried it with a local mosquitto as the broker and it basically just works, although it's probably not very robust. Open questions for me are:

- What data exactly should be sent over MQTT? Currently, the code uses the same `build_data` method as `GcmPushkin` did to build a dictionary, dumps it as JSON and publishes it over MQTT.
- Under which topic should a notification be published? Currently, we just publish it to a topic named the same as the pushkey for the device. I could then imagine devices that want to receive the notification to connect to the broker with the pushkey as their client id while the broker should be configured such that clients can only subscribe to topics that match their client id. That way only who knows the pushkey for a specific device can subscribe to the notifications. (I'm not sure if the pushkey is meant to be used like that...)
- Which options should be exposed in `sygnal.conf`? An MQTT broker could run on a different port and most brokers also allow authenticating using a client certificate instead of username and password.

This is my first contact with MQTT so I could be entirely off-track. Thus, I would love to hear from people that have more experience with it. :wink:

@jcgruenhage, @ara4n

### CODE REVIEW

**Comment by ara4n** [comment]
oooooooh! this looks very very cool!  sygnal is @dbkr's baby, so i suspect he has some thoughts here.  The data sent to GCM or APNS is a very good start - the alternative would be to poke the app to wake up and do a sync itself, but if we can avoid doing that it'll certainly save battery & bandwidth.

Have you tried hooking it into a client (e.g. matrix-android-sdk) yet?

**Comment by jooert** [comment]
> The data sent to GCM or APNS is a very good start - the alternative would be to poke the app to wake up and do a sync itself, but if we can avoid doing that it'll certainly save battery & bandwidth.

MQTT allows arbitrary data to be send, so we can just send the notification instead of only poking the client. However, we probably have to fix the format of the notification data to be sent. (That's probably a reason why it would be good to implement client support in matrix-android-sdk instead of Riot itself.)

> Have you tried hooking it into a client (e.g. matrix-android-sdk) yet?

No, not yet, although that's definitely something I want to try out.

**Comment by dbkr** [comment]
This is cool! I have no experience with MQTT personally but it looks plausible from a sygnal point-of-view. Is there an example of a client that uses it?

**Comment by jooert** [comment]
No, although I would love to see Riot on Android supporting it (relevant issue is https://github.com/vector-im/riot-android/issues/1066).

**Comment by richvdh** [comment]
this seems to be bitrotting

**Pull request closed without merging**
