### PR TITLE
Upgrade development dependencies #199

### LINKED ISSUE #199: Upgrade development dependencies
Right now our [setup.py](https://github.com/matrix-org/sygnal/blob/ae797c739e13aca378e6de35d4a31e088cb619b7/setup.py#L57-L61) specifies exact versions of black, flake8, mypy, etc. We should update those to the latest versions and make sure the lints still pass.

It's probably easiest to do one commit per dependency, e.g.:

1. Update Black's version to [the latest](https://pypi.org/project/black/)
2. Run `tox --recreate` to pick up the new version of the library and see if anything is broken
3. Fix anything broken
4. Run `tox` to verify that everything is working
    (you don't need `--recreate` here since you already did that in step 2 above)
5. Commit your changes

### PR DESCRIPTION
**Pull request by kibablu**
Upgrade development dependencies (#199)

upgrade dependencies in [setup.py](https://github.com/matrix-org/sygnal/blob/ae797c739e13aca378e6de35d4a31e088cb619b7/setup.py#L57-L61)

fixes #199

### CODE REVIEW

**Review by callahad — CHANGES_REQUESTED** [review]
Looks like we also need to run `black` on the `tests/` directory (see logs at https://buildkite.com/matrix-dot-org/sygnal/builds/548#1770db00-bf3e-4c60-b9ef-72f0b8418ace/133-150 for more info)

**Comment by kibablu** [comment]
> Looks like we also need to run `black` on the `tests/` directory (see logs at https://buildkite.com/matrix-dot-org/sygnal/builds/548#1770db00-bf3e-4c60-b9ef-72f0b8418ace/133-150 for more info)

got the same error logs after running `black` on the `tests/` directory 
tests
tests-1

**Comment by callahad** [comment]
Looks good! Thank you for doing this :)

**Review by callahad — APPROVED** [review]

**Comment by callahad** [comment]
(I honestly expected `black` to make more changes than it did 😆)

**Comment by kibablu** [comment]
> Looks good! Thank you for doing this :)

Thank you also, learning a lot here :smiley:

**Pull request merged**
