### PR TITLE
Improve static type checking #201

### PR DESCRIPTION
**Pull request by kibablu**
Add static type checking on setup.py with `Any` as the path-like object is either an `str` or `bytes` object representing a path, or an object implementing the os path.

### CODE REVIEW

**Comment by callahad** [comment]
It looks like this Git branch has all of your other changes on it... could you please rebase so it's just the static typing ones?

`git fetch origin && git rebase -i origin/master` should do it. Then, when things look right, you should be able to `git push --force-with-lease` to update this pull request.

**Comment by kibablu** [comment]
Should I switch the branch to `master` and then rebase while I'm in `master`?

**Comment by kibablu** [comment]
`git fetch origin && git rebase -i origin/master` should this run while on the `master` branch or my other branch. Thank you

**Comment by callahad** [comment]
`fetch` can be run on any branch, since it doesn't modify your checked out work, but the `rebase` needs to happen when you're on your feature branch, since the goal is to re-play that branch on top of `origin/master`

**Review by richvdh — CHANGES_REQUESTED** [review]
As @callahad mentioned, this PR has some unrelated changes in it.

@kibablu: remember that you can see the changes in this PR at https://github.com/matrix-org/sygnal/pull/218/files: you should be able to see what we mean about unrelated changes.

**Comment by callahad** [comment]
Closing in favor of #221

**Pull request closed without merging**
