### PR TITLE
ApnsPushkin improvements

### PR DESCRIPTION
**Pull request by morozkin**
Signed-off-by: Denis Morozov dmorozkn@gmail.com

### CODE REVIEW

**Comment by dbkr** [comment]
This changes pushes for image messages from, "Bob in Cats: image.jpg" to "Bob posted a picture in Cats"

@ara4n @lampholder @AmandineLP yay or nay? Personally I like having that little bit more information about what the image might be (eg. coffee.gif)

**Comment by ara4n** [comment]
yeah, i would prefer to keep the filename or other details too...

**Comment by morozkin** [comment]
@dbkr wdyt?

**Comment by dbkr** [comment]
Yep, let's do that then. The annoyance is that if the string isn't in the strings file, it'll just display the raw string sent by the server, so I think we'll have to make sure everyone has updated before we start sending the new string.

**Comment by giomfo** [comment]
FYI the strings have been updated on client side (on develop)
https://github.com/vector-im/riot-ios/pull/1486

**Pull request merged**
