### PR TITLE
Use absolute imports for consistency

### PR DESCRIPTION
**Pull request by squahtx**

### CODE REVIEW

**Review by DMRobertson — APPROVED** [review]
I'm keen for consistency, and neutral on whether we should prefer relative or absolute imports.

Is there a linter check we can use to enforce this?

**Comment by richvdh** [comment]
> I'm keen for consistency, and neutral on whether we should prefer relative or absolute imports.

I thought this was explicitly covered by https://github.com/matrix-org/synapse/blob/develop/docs/code_style.md, but it seems I thought wrong.

In the absence of our own rules, we generally defer to Google's style guide, which is generally comprehensive and well-reasoned. In this case it [says](https://google.github.io/styleguide/pyguide.html#23-packages):

> Import each module using the full pathname location of the module.

**Comment by richvdh** [comment]
(and [also](https://google.github.io/styleguide/pyguide.html#224-decision):

> Do not use relative names in imports. 

)

**Comment by squahtx** [comment]
> Is there a linter check we can use to enforce this?

A quick search found https://github.com/MarcoGorelli/absolufy-imports which will reformat your imports, and https://pypi.org/project/flake8-absolute-import/

**Pull request merged**
