### PR TITLE
setup coverage.py in tox env

### PR DESCRIPTION
**Pull request by H-Shay**
Hopefully this satisfies the first part of https://github.com/matrix-org/sygnal/issues/200#issuecomment-819410266. If so, I'll move on to adding reports to Github actions, etc. Thanks!

### CODE REVIEW

**Comment by H-Shay** [comment]
Noting that the towncrier github actions check is failing. Looks like an error with a config file somewhere (git produced output while failing:
fatal: ambiguous argument 'origin/master...': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]')
I didn't experience this error when setting up the github actions so I'm a little perplexed, but I will look deeper into it tomorrow.

**Comment by anoadragon453** [comment]
The command that `towncrier` is running is `git diff --name-only origin/master...`, and failing to figure out what `origin/master` is. There's a lot of possible reasons for this. `checkout@v2` might be specifying your fork as `origin`, and may only be checkout out your `add-coverage` branch but nothing else. It may be possible to fix this by just doing a `git fetch origin` before running `towncrier`.

I'd probably play around in this PR (or another) and try to get some information out of GitHub Actions in terms of how it's set it's remotes and branches up.

**Comment by callahad** [comment]
Looks good!

- Let's add `.coverage*` and `htmlcov/` to the `.gitignore` file and remove them from this pull request; no need to ship the reports with our source.
- It would probably be good to run `coverage report --sort=cover` _and_ `coverage html` so that there's something in the console as well as the html if you want to delve deeper.
- ...and maybe only run the report(s) if the initial `-m twisted.trial` succeeds?

**Comment by callahad** [comment]
As to the towncrier bit... by default GitHub Actions does a shallow clone of the repo which has only one commit: the result of the proposed merge. So there's no actual history there to compare against. Solving that properly is a bit of a rabbit hole, but I _think_ setting:

```
- uses: actions/checkout@v2
  with:
    fetch-depth: 0
    ref: ${{ github.event.pull_request.head.sha }}
```

would get you a full history, check out the actual branch head (not the proposed merge) and allow the check to work.

**Comment by H-Shay** [comment]
Ok cool I will open a different PR for the towncrier issue and see if I can't get it working using the insight you both offered. 

I've updated the PR to add the other changes related to coverage. However I have one question:

In terms only running the coverage reports if the `-m twisted.trial` succeeds, I am wondering if tox doesn't do this automatically? Looking at the docs, under **commands** it states that "Commands will execute one by one in sequential fashion until one of them fails (their exit code is non-zero) or all of them succeed." My understanding of this is that tox will exit if the `twisted.trial` fails. I am unfamiliar with tox so please correct me if I'm wrong!

**Comment by callahad** [comment]
> "Commands will execute one by one in sequential fashion until one of them fails (their exit code is non-zero) or all of them succeed."

Oh, cool! You're probably totally good there, then :)

**Comment by H-Shay** [comment]
Great then this should be all set to go!

**Comment by richvdh** [comment]
@callahad I think you have most context here so if you have the cycles to pick up the review that would be appreciated!

**Review by callahad — CHANGES_REQUESTED** [review]
Great, thanks! Could you please:

1. Merge `origin/master` (or rebase onto `origin/master`) so we can get working towncrier checks
2. Add `coverage~=5.5` as a dependency somewhere to ensure that a clean`tox` virtual environment has access to it? (e.g., it could be a dev dependency in setup.py, or a one-off `deps` entry in the `tox.ini` testenv.

**Comment by H-Shay** [comment]
Alright I think that did it. Thank you!

**Comment by callahad** [comment]
We're almost good :) The `tox.ini` still needs to be adjusted to actually install `coverage` in the default testenv. You can just remove the `extras =` stanza from the other environments and put it straight in the base `testenv` and then all three will inherit it and install the `dev` dependencies.

**Comment by H-Shay** [comment]
Thanks for the hand-holding, I am actually learning a lot. Hopefully this is the last update!

**Review by callahad — APPROVED** [review]

**Comment by callahad** [comment]
Thank you so much!

**Comment by callahad** [comment]
Oh, hey, could you sign-off on a commit in this branch, please?

You can do a `git commit --signoff --allow-empty` to make an empty commit to that effect :)

**Pull request merged**
